### ISSUE TITLE
(3) Display Citations for Items

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#115]
### Descriptive Summary

Provide properly formatted citations in MLA, APA, and Chicago styles for each item.

### User Story

As a user, when I click the Cite button, a modal pop up where I can copy the APA, MLA, or Chicago style formats so that:
- I can copy a properly formatted citation for an item
- I have a choice between the most popular citation formats

### Mock Ups:

**Example of Cite button with quote icon:** 
![Screen Shot 2019-11-20 at 3 49 36 PM](https://user-images.githubusercontent.com/9621070/69288094-616cf600-0bad-11ea-9051-74d092f99de2.png)

**Example of modal with three citation format options to copy:**
![Screen Shot 2019-11-20 at 3 39 19 PM](https://user-images.githubusercontent.com/9621070/69287675-f0790e80-0bab-11ea-87c4-ffd91ddfbd51.png)

**Example from UC Davis:**
![Screen Shot 2019-11-13 at 2 33 16 PM](https://user-images.githubusercontent.com/6412857/68810316-bb584380-0622-11ea-8ca5-d598e4350ff5.png)

### Background 

Originates from Journey Map: Serena at the Reference Desk

### Acceptance Criteria

This is what done looks like

* [ ] Cite button on Works page (includes quote logo) 
* [ ] Modal pops open on click  
* [ ] Citations are displayed for each item
* [ ] Citations are property formatted using MLA, APA, and Chicago styles
* [ ] End-users can easily copy a citation

### Implementation Steps:
Note Hyrax already has a link where MLA, APA, and Chicago Formats are displayed:

![Screen Shot 2019-11-20 at 4 06 06 PM](https://user-images.githubusercontent.com/9621070/69288890-bf9ad880-0baf-11ea-99b9-32a8bf2b6d46.png)

**Comment by rschwab** [comment]
@JessWaggs I used bootstrap tooltips for the interaction with the copy buttons. Please let me know if you want any adjustments to the interaction.

Screenshots:
![Firefox_Screenshot_2020-02-24T18-20-03 797Z](https://user-images.githubusercontent.com/515412/75179886-e6593580-56ef-11ea-8a5a-b14de1e26fa4.png)
![Firefox_Screenshot_2020-02-24T18-20-23 200Z](https://user-images.githubusercontent.com/515412/75179900-ebb68000-56ef-11ea-935d-18ba2e099782.png)

**Comment by NedHenry** [comment]
This looks and works great for me! I just added a couple of commits refactoring a little bit to adhere better to conventions. Let me know if any of this raises any red flags for you, Ryan.
- I broke the _modals.html.erb view partial into _citations_modal.html.erb and _download_modal.html.erb, and moved the conditional logic for when to display them into the show.html.erb. I think this is slightly more clear, and follows Hyrax's convention of making very small view partials that are specifically named for their function.
- I moved the javascript related to the citations into its own javascript file that gets loaded as part of the Rails asset pipeline. That means it'll get compiled into our main javascript bundle, which is downloaded by the user once the first time they visit our site and then cached. This speeds up page load time by avoiding the download of embedded javascripts every page load, and also keeps our javascripts all in one place.
- I removed the lines that initialize the bootstrap tooltips. I'm pretty sure there was a typo/error that kept this line from running anyway, but the functionality still works fine because bootstrap tooltips are apparently initialized elsewhere in Hyrax's native javascript packages. 

Cheers!
