### ISSUE TITLE
Set up authentication for our image server

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#119]
### Sub-Issues
This issue is broken up into the following sub-issues:
- #156 
- #155 
- #157 
- #159 

### Descriptive Summary

Current behavior: Requests for images from our image server (e.g. through the Universal Viewer) are currently not authenticated by the image-server. Direct links to these images can be copied from our source code and re-used in malicious ways even after we disallow access to our content in Hyrax. While these links are not provided to users in any obvious way, they can be easily extracted from our source code.

 Expected behavior: The image server runs an authentication protocol on all image requests. Images that are restricted in our DAMS require the user to have a special cookie granted by our rails application to gain access. These cookies expire, so it is impossible to gain direct and sustained access to our images without our permission.

### Background 

IIIF has a protocol for authorization and authentication, but it doesn't necessarily have a lot of implementations of that protocol. The universal viewer claims to support this authorization protocol, which is heartening, but without good documentation of this support it is unclear how to configure the UV to work with a particular authentication server. 

The idea is that our application gives the users cookies that verify their identity with respect to our dams. Then the universal viewer uses that cookie to ask the dams whether this identity has access to that resource, and gets an access token if appropriate. The access token is necessary to access the image itself. The procedures for how that ought to work are all laid out in the IIIF specification, but the mechanics of generating these tokens and cookies in a Hyrax context are not implemented anywhere obvious (to me).

None of this is conceptually groundbreaking or super difficult, but all together it is more work that we would ideally want to do on our own if we can help it. We should do this along with other Hyrax institutions if we can.

This issue came out of work on #109 

### Acceptance Criteria

* [x] We have a clear picture of how other Hyrax institutions are doing IIIF image authentication
* [x] We have chosen a strategy for image authentication and articulated our reasons for choosing it
* [x] All requests to our image server are authenticated

**Comment by kellyChex** [comment]
@NedHenry I've sent a non urgent message to Julie and Rob to see if they have any insight here before pining the general Hyrax channel.

**Comment by NedHenry** [comment]
# Expected Behavior:
## When Logged Out:
- [ ] After clearing your browser cookies and cache, if you navigate directly to a [public image on the image server](https://digitalcollections-image.library.ucsc.edu/staging/iiif/2/sn_00_9x_76_k/full/800,/0/default.jpg) without first visiting our DAMS, you will be forbidden (to prevent hotlinking)
- [ ] You can view public images in the DAMS [with](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/h989r3203?universal_viewer=true) and [without](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/h989r3203) using the universal viewer
- [ ] [Private images](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/gb19f580q) do not display through the dams
- [ ] Private images do not display when navigating directly to [image server link](https://digitalcollections-image.library.ucsc.edu/staging/iiif/2/qn_59_q3_96_v/full/800,/0/default.jpg)
- [ ] After navigating through the DAMS, without clearing your cookies, you may view an image directly at its [url on the image server](https://digitalcollections-image.library.ucsc.edu/staging/iiif/2/sn_00_9x_76_k/full/800,/0/default.jpg)

## When logged in as an administrator:
- [ ] Public images display in the DAMS, [with](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/h989r3203?universal_viewer=true) and [without](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/h989r3203) using the universal viewer
- [ ] Private images display through the dams [with](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/gb19f580q?universal_viewer=true) and [without](http://digitalcollections-staging-sandbox.library.ucsc.edu/concern/works/gb19f580q) the universal viewer

# Instruction for quality control: 
- You should have received an email with your admin login information for this site
- Log in to the campus VPN before accessing the site (just like for the other staging site)
- Pick a browser to test. I've already tried it on Firefox, so maybe pick a different one just so we get more information.
- Follow the links in the "Expected Behavior" section in order, logging in to the DAMS when you get to the appropriate section
- Make a note if you encounter any problems and comment either here or on slack

**Comment by kellyChex** [comment]
I also tested. Works well!

**Comment by NedHenry** [comment]
It sounds like this is working as expected on multiple different browsers. Unless someone objects I will consider this ready for deployment.

**Comment by kellyChex** [comment]
I tested the above acceptance criteria against a Black Panther work http://digitalcollections.library.ucsc.edu/concern/works/bc386j502?universal_viewer=true#?c=0&m=0&s=0&cv=0&xywh=-6237%2C-1%2C23199%2C7527 and correctly doesn't allow me to view the image if not logged in. Still need to confirm the same is true directly on the image server just not sure how to navigate there?

**Comment by kellyChex** [comment]
@NedHenry It appears you can see private images on the image server on production, when not logged in: https://digitalcollections-image.library.ucsc.edu/iiif/2/b5_64_4r_68_r/full/800,/0/default.jpg

**Comment by NedHenry** [comment]
@kellyChex I just looked this up - this problem is actually (strangely) unrelated to this issue, although it is important and it highlights the importance of this QA work. The problem is that these works are marked private (`work.visibility = "restricted"`) but the file sets they contain (the image themselves) are marked public (`file_set.visibility = "open"`). I think this is because these works were altered by the partially-applied MS0020 update and automatically un-published during that process (for QA, theoretically). I was going to finish the MS0020 update before re-publishing these, but I could easily do so now as well.

**Comment by NedHenry** [comment]
For the purposes of this QA task, here are:
[a fully published work](http://digitalcollections.library.ucsc.edu/concern/works/1c18df916)
[the direct image link associated with the public work]()
[a fully private work](http://digitalcollections.library.ucsc.edu/concern/works/9z9030116?locale=en)
[the direct image link associated with the private work](https://digitalcollections-image.library.ucsc.edu/iiif/2/bz_60_cw_43_z/full/800,/0/default.jpg)

**Comment by kellyChex** [comment]
@NedHenry Ok, keep @chesleyperry and I posted on when we can QA this again.

**Comment by kellyChex** [comment]
Created a private test collection in production, http://digitalcollections.library.ucsc.edu/concern/works/zp38wg10c?locale=en, and all scenarios above passed.
