### ISSUE TITLE
(5) Get CLIR/CMF collection metadata & files ready for ingest 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#17]
### Descriptive Summary

New CMF (not the pilot): review archival inventory; determine what addition metadata can/should be added. Updating/enhancing metadata work will become priority after tapes returned/DI review of files (end Oct/beg Nov).  Tape inventory lists physical media, while the metadata spreadsheet needs list files and performances. 

### Background Information
**Collection Title:** Cabrillo Music Festival of Contemporary Music Recordings Collection

**Collection Call Number: MS 414**
**rightsStatement:** This work is available from the UC Santa Cruz Library upon request. Please contact Special Collections & Archives for access. This digital copy of the work is intended to support research, teaching, and private study. This work is protected by U.S. Copyright Law (Title 17, U.S.C.). Use of this work beyond that allowed by fair use requires written permission of the copyright holder(s). Responsibility for obtaining permission, and for any use or distribution of this work, rests exclusively with the user and not the UC Santa Cruz Library. For more information on copyright, please visit: guides.library.ucsc.edu/speccoll/reproduction-publication.
**rightsHolder:** N/A
**accessRights:** Restricted
**rightsStatus:** [In Copyright](http://rightsstatements.org/vocab/InC/1.0/)
**donorProvenance:** Original tape gift of Other Minds.
**Finding Aid:** https://oac.cdlib.org/findaid/ark:/13030/c8wq0984/

**Collection Call Number: MS 64**
**rightsStatement:** This work is available from the UC Santa Cruz Library upon request. Please contact Special Collections & Archives for access. This digital copy of the work is intended to support research, teaching, and private study. This work is protected by U.S. Copyright Law (Title 17, U.S.C.). Use of this work beyond that allowed by fair use requires written permission of the copyright holder(s). Responsibility for obtaining permission, and for any use or distribution of this work, rests exclusively with the user and not the UC Santa Cruz Library. For more information on copyright, please visit: guides.library.ucsc.edu/speccoll/reproduction-publication.
**rightsHolder:** N/A
**accessRights:** Restricted
**rightsStatus:** [In Copyright](http://rightsstatements.org/vocab/InC/1.0/)
**donorProvenance:** Original tape gift of the Cabrillo Festival of Contemporary Music.
**Finding Aid:** https://oac.cdlib.org/findaid/ark:/13030/c81v5mfm/

### Acceptance Criteria

Spreadsheet and files are ready to ingest into the DAMS.  

### Tasks

DI:
- [x] Change filenames to remove _ORIG and _MOD
- [x] Change filenames to match collection names (add 0 to ms0046) 
- [x] Update spreadsheet to match collection names
- [x] Update spreadsheet to add .wav to accession numbers for filenames
- [x] Check spreadsheet and filenames to make sure they match.  Pay particular attention to splits and merges.  When the number of files doesn't match the spreadsheet, listen to the recordings and update the sheet.

Metadata:
- [x] Split title and composer metadata into the rows below for splits
- [x] Remove unnecessary metadata columns
- [x] Add necessary metadata columns
- [x] Create parent rows for the concerts and add parent metadata (titles, extent, etc.)
- [x] Add "Part #:" prefixes to child titles
- [x] Verify which composers are associated with which pieces
- [x] Add authorities for composers and locations, when possible
- [x] Resolve typos, diacritics, spacing and other formatting issues
- [x] Format spreadsheet for ingest spec

**Comment by rmjaffe** [comment]
@tmariamora @katedundon When you have a chance, please add the information that is missing for MS 64 (see the "Background" section above).  You can add the information directly to the ticket window, by clicking the ellipsis (...) in the top right corner of the pane and selecting edit.  When you're done, click "update comment."

**Comment by rmjaffe** [comment]
@tmariamora @katedundon Could I ask you to provide a collection-level description of the "collected" Cabrillo Music Festival of Contemporary Music Recordings Collection?  I found descriptions of MS 64 and MS 414 in OAC, but I'd rather put the question to you than supply a hybridized description of my own making.

**Comment by katedundon** [comment]
Sure, I can work on and get back to you within a few days.

**Comment by katedundon** [comment]
@rmjaffe please a collection-level description for the Cabrillo recordings here: [CMF Digital Projects Planning Worksheet/MOU](https://docs.google.com/document/d/1x2JFxNHO-wvOg6L8V9m5pTAPkAtdGHl20eRZCL5gQL4/edit?usp=sharing) (see last page)

**Comment by rmjaffe** [comment]
@chesleyperry CMF metadata is ready for review!  I put a copy of the spreadsheet in the folder on dams_ingest: smb://artifacts.library.ucsc.edu/dams_ingest/ms0414_CMF_round2.

Once you've finished your final review, would you please close this ticket and move it to done?
