### ISSUE TITLE
Combined Campus History Ingest

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#271]
### Descriptive Summary

In order to move off CONTENTdm, the combined campus history collection needs to migrate to the new system.  This will include: updating the flexible metadata model (collection of collections metadata); preparation, ingest, and QA of the metadata and files: and updates to UI to properly display the collection of collections metadata.

### Acceptance Criteria

This is what done looks like:

**Files & Metadata**
* [x] #19 Review combined campus history for possible remodel
* [x] #152 Prepare ingest spreadsheet for combined campus history collections
* [x] #12 Finish updating filenames and fixing issues with combined campus collections
* [x] #13 Move files for combined campus collections into one directory on dams_ingest
* [x] #190 UCSC campus maps addition to combined campus history spreadsheet)
* [x] #41 Ingest combined campus history collections
* [x] QA Ingested Combined Campus History Collection - Pre-publish #364
* [x] #120 Campus history photograph collections: removal of bucket containing combined campus history collections and UA 50 from CONTENTdm

**Collection of Collections Metadata**
* [x] #234 Research on Collections of collections
* [x] #285 Determine best strategy for adding collection-level metadata for older collections 
* [x] #238 Determine tickets for collection of collection metadata implementation
* [x] Test ingest with nested collections (collections of collections) #347 

**Collection of Collections Landing Pages**
* [x] #153 Mock up for collection of collection and collection landing pages
* [x] #231 Create Collection Group (Collection of Collections) pages
* [x] Determine display details for complex image objects #345
* [x] Design any necessary front-end for nested collection display #348
* [x]  Implement nested collection display #350 

### Related Work 

This is an test epic created as part of #270 Creating/testing epics to track project progress.

**Comment by rmjaffe** [comment]
Before we get in the weeds on this one, we will need to:

1. Nail down the date CONTENTdm must be upgraded by @chesleyperry 
2. Move #231 out of the Icebox
3. Create tickets described in #238

**Comment by rmjaffe** [comment]
@chesleyperry When you wrap up #120, would you mind closing out this epic? :)
