### ISSUE TITLE
CLIR Grant: CMF Ingest

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#272]
### Descriptive Summary

In order to satisfy the requirements of the CLIR grant, the CMF ingest needs and creation of the  first tier, MVP virtual reading room needs to be completed.  

The major components of this project were: the preparation, ingest and QA of files and metadata; introduction of the collection-level metadata and collection landing pages; and setting up IP restricted access to the collection.

### Background 

Link to CLIR grant documentation: https://drive.google.com/drive/folders/132HFaJNxkdRlizs6ylAArKWR3W7Hprq1?usp=sharing
Project deadline: October 2020

### Acceptance Criteria

This is what done looks like:

**Metadata & Files**
* [x] #17 Get CMF metadata & files ready for ingest
* [x] #242 Ingest of CMF metadata & files
* [x] #10 Develop workflow reqs for QC of audio files post-ingest
* [x] #268 Fix ~10 broken audio files from CMF ingest
* [x] #266 1st Round QA
* [x] #267 2nd Round QA

**Collection-Level Metadata**
* [x] #154 Customize collection-level metadata schema to match work-level schema
* [x] #103 Update metadata ingest software to accommodate collection-level metadata
* [x] #235 Create test spreadsheet for collection-level metadata
* [x] #236 Update ingest spec doc for collection-level metadata

**Merging CMF Pilot and CLIR Grant Ingests**
* [x] #283 Fix display order of tracks in CMF pilot ingest
* [x] #274 Merge Pilot CMF collection into the second ingest

**MVP Virtual Reading Room**
* [x] #25 Create user experience requirements
* [x] #241 Get full set of campus IP ranges
* [x] #246 Implement restriction and display for users on campus IP
* [x] #248 Implement restriction and display for users NOT on campus IP
* [x] #244 Create "learn more" LibGuide

**UI Work**
* [x] #153 Mock up for collection landing pages
* [x] #131 Add About collection section
* [x] #176 Apply new collection landing page design: Desktop
* [x] #222 Create collection landing page description box
* [x] #275 Configure CMF collection landing page
* [x] #276 Apply new collection landing page design: Mobile

### Related Work
This is an test epic created as part of #270 Creating/testing epics to track project progress.
...
