### ISSUE TITLE
CONTENTdm Migration

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#288]
### Descriptive Summary

This epic pulls together the work required to exit CONTENTdm.  This includes the steps required to: 

- Relocate legacy digital collections:  evaluating collections, preparing them for ingest and republication them in the DAMS, making them accessible elsewhere, or deaccessioning them. 
- Remove legacy digital collections from CONTENTdm:  updating and redirecting links, taking down collections, etc.
- Reshare legacy collections: (re)harvest to Primo and Calisphere, update of external resources (e.g. Wikipedia).

These actions are documented on cards created for each legacy collection. Cards pertaining to the actual ingest, QA and publication of legacy collections in the DAMS will be created separately as needed.

### Background

This epic serves as "mega"-epic:  cards belonging to the this epic may be included in smaller ingest focused epics, for example, #271 Combined Campus History Ingest.

### Acceptance Criteria

This is what done looks like:
_Collections are listed in order of priority_

Combined Campus History Collections
* [ ] Combined Campus History Collections #41 
* [ ] UCSC Campus Maps #190
* [ ] Ingest of Combined Campus History Collections & UCSC Campus Maps #54
* [ ] Takedown of Campus History Photographs Cdm Bucket #120 

Ansel Adams (MS 2)
* [ ] Pre-/Post-Ingest Ansel Adams #48
* [ ] Ingest Ansel Adams #284 

DeCou (MS 38)
* [ ] Pre-/Post-Ingest DeCou Collection #158 
* [ ] Ingest DeCou #57

Lick Observatory (UA 36)
* [ ] Pre-/Post-Ingest Lick #169
* [ ] Ingest Lick #56 

Kofsky Images (MS 312)
* [ ] Pre-/Post-Ingest Kofsky Images
* [ ] Ingest Kofsky Images

Alexander Lowry (MS 188)
* [ ] Pre-/Post-Ingest Lowry #204
* [ ] Ingest Lowry #62 

Vester Dick (MS 235)
* [ ] Pre-/Post Ingest Vester Dick #203
* [ ] Ingest Vester Dick #60 

Chuck & Esther Abbott (MS 39)
* [ ] Pre-/Post Ingest Abbott #205
* [ ] Ingest Abbott #61 

Aerial Photos
* [ ] Pre-/Post Ingest Aerials #168
* [ ] Ingest Aerials #70
