### ISSUE TITLE
Longer-term Licensing of Kakadu & Performance Evaluation

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#304]
### Descriptive Summary

We want to arrive at a decision on whether to purchase a long term license for the JPEG2000 image processing utility Kakadu, which we are currently using in an evaluation capacity.  If we decided to go forward with the purchase, we will want to do some further troubleshooting and evaluation of Kakadu's performance.

### Background 

From #186: We recently implemented Kakadu (#121) and started creating JPEG2000 derivatives for each of our imported images, which vastly improved the speed of our IIIF image viewing experience (#36 Fix UV performance issues). The Kakadu software is a third party extension that we now have a six month evaluation license for, and we are planning to purchase a long term license if we can negotiate favorable terms.

### Acceptance Criteria

This is what done looks like:

* [x] Decision on whether to purchase long-term license for Kakadu #149 
* [x] Evaluate kakadu performance on encoding our large TIF collections #150 
* [ ] Contact Kakadu and get quote for license #149 
* [ ] Fix ingest of jpegs & compressed TIFFs #186
