### ISSUE TITLE
User Interface Redesign

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#311]
### Descriptive Summary

This epic aggregates the tickets for the DAMS user interface overhaul. These include tickets for the mock ups of new or revised pages in desktop and mobile and tickets for the application of those mock ups.

### Background 

It is anticipated that pages/layouts for new item types (such as text documents or maps) will be added to this epic.

### Acceptance Criteria

This is what done looks like:

**Homepage:**

* [ ] #146 Mock Up for Homepage (desktop and mobile)
* [ ] #279 Apply new homepage design (desktop)
* [ ] #280 Apply new homepage design (mobile)

**Header and Footer:**
* [ ] #145 Mock Up for Header and Footer (desktop and mobile)

**Application Tickets:**

### Best Practices for UI Tickets:

- Create two separate application tickets: one for desktop, one for mobile
- Include mock up ticket as a related issue in the application ticket
- Include desktop/mobile ticket as a related issue in the application ticket
- Use the term "Apply" in ticket titles for the redesign of an existing page using existing elements
- Use the term "Create" in ticket titles for the development of new pages or new elements

**Comment by alpha2320** [comment]
i will like to work on this
