### ISSUE TITLE
Ingest of Remaining Non-Core Cdm Legacy Collections

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#386]
### Descriptive Summary

This epic pulls together the work needed to get our remaining, non-core CONTENTdm legacy collections up in the DAMS, excluding the campus publications and the aerial photographs collection.

This epic follows UCSCLibrary/dams_project_mgmt#288 CONTENTdm Core Migration epic.

### Background 
These collections have been identified as being both more challenging and of a lower priority for migration/ingest into the DAMS.

### Acceptance Criteria

**Hitchcock Photo Catalogue**
* [ ] Pre-Ingest Hitchcock UCSCLibrary/dams_project_mgmt#202
* [ ] Ingest Hitchcock UCSCLibrary/ucsc-library-digital-collections#338 
* [ ] Post-Ingest Hitchcock photography catalogue UCSCLibrary/dams_project_mgmt#302

### Map Collections - _these require further decision making_
* [ ] Standard Map Service Atlases UCSCLibrary/ucsc-library-digital-collections#343 
* [ ] UCSC Library Maps UCSCLibrary/ucsc-library-digital-collections#344
