### ISSUE TITLE
(3) Check and fix metadata inheritance

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#39]
### Descriptive Summary

Note from Ned: 
A lot of times, child works share most of their metadata with their parent works. We have come up with a system in which we can specify that the child work inherits certain metadata fields, so we don't have to enter them for every child work in a series. This is mostly working but it needs test coverage, debugging, and some actual works to test it on.

### Tasks 
- Rachel to update the Ingest specification document with the inheritance rules, https://docs.google.com/document/d/1uTCld2UkvQUKILKIMDp4FLH3ogimZ_J58Zu92ALZUc0/edit 
- Ned needs to update the bulk ingest code to accommodate the inheritance rules 
- Ned to create automated tests

### Acceptance Criteria

This is what done looks like
* [x] Rachel to update spec doc 
* [x] Ned updated the bulk ingest code 
* [x] Automated Tests - nearly full test coverage
* [x] CMF Pilot works should be tested against

**Comment by NedHenry** [comment]
Small change from what I said before - I am actually implementing this feature in our DAMS codebase rather than in the BulkOps gem. This will give us more flexibility over how, where, and when the inheritance occurs in our system - for example, if we make a manual change to a work's metadata in a browser, this approach it will make it easy to propagate that change to the work's children based on these inheritance rules.

**Comment by NedHenry** [comment]
I added code to ensure that whenever a work is saved, appropriate metadata fields are populated from the work's parent work and saved in Fedora. I wrote tests to make sure that this inheritance happens only under the appropriate circumstances. Those tests now pass. 
Because it was unclear to me at first how we wanted this to work, I have also written code to allow for a few more use cases that we won't be using yet. I added the feature to let metadata inheritance happen when the work is indexed instead of saved, so the inherited metadata is attached to the child record only in Solr and not in Fedora. The metadata inheritance can aslo happen when the work is displayed, without storing the inherited metadata in either Solr or Fedora. We also don't plan to use those features. 
relevant commits:
4c1641534bc7a0403829c06411036dbf59089ff1
15aca1afc835ced25f8b15275062e1c9e5d0ebce
8eab8ac4054b5c0aaf99e1ed9f7662eb3dde8f38

**Comment by kellyChex** [comment]
@rmjaffe and @NedHenry agreed to consolidate https://docs.google.com/document/d/1uTCld2UkvQUKILKIMDp4FLH3ogimZ_J58Zu92ALZUc0/edit and https://docs.google.com/document/d/1Y8u805F5ucRPLiZeJZ1zJk_65GwG1JB0ka6ytfJRXwU/edit#heading=h.d14nbrpy87ii. Rachel has already reviewed both documents and feels like a conversation needs to happen at this point to clear up some questions.
