### ISSUE TITLE
Preparation and Ingest of the Aerial Photographs Collection

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#433]
### Descriptive Summary

This epic pulls together the work required to prepare and ingest our legacy aerial photographs collection into the DAMS.

### Acceptance Criteria

* [ ] Pre-Ingest Aerials UCSCLibrary/dams_project_mgmt#168
* [ ] Ingest Aerials UCSCLibrary/ucsc-library-digital-collections#372 
* [ ] Post-Ingest Aerial Photographs Collection UCSCLibrary/dams_project_mgmt#300

### Related Work

This epic follows the CONTENTdm Core Migration epic UCSCLibrary/dams_project_mgmt#288 
Support for Cartographic Material UCSCLibrary/dams_project_mgmt#392

**Comment by rmjaffe** [comment]
@chesleyperry @afrebert I'm in the process of creating separate epics for work on the aerials and on the campus pubs.  Do you want to include a link here to your aerials project board?  Please feel free to add to or edit this epic card.
