### ISSUE TITLE
Bulk Ops Overhaul

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#436]
### Descriptive Summary

This epic pulls together outstanding and anticipated improvements we want to make to our bulk ingest process.  This work is not urgent but it would eliminate/reduce the need for some of the workarounds that are currently in place.  It would also make our code more shareable.

This epic is organized into two parts:

1. Testing our bulk ingest code, which in part involves creating tasks to be tested
2. Resolving known errors in the code which have been previously documented

### Acceptance Criteria

This is what done looks like:

**Part 1: Testing**
* [ ] _These criteria need to be developed and cards created_

**Part 2: Reproducing and resolving known issues**
* [ ] Ingested filesets on complex objects are not named or ordered properly UCSCLibrary/dams_project_mgmt#415
* [ ] Evaluate implementation of "Order" feature in ingest spreadsheets UCSCLibrary/ucsc-library-digital-collections#383 
* [ ] Permission conflicts in shared derivative drive UCSCLibrary/dams_project_mgmt#378 
* [ ] Sometimes filesets are not fully attached to their works UCSCLibrary/dams_project_mgmt#252 
* [ ] Fix ingest of jpegs & compressed TIFFs UCSCLibrary/dams_project_mgmt#186 
* [ ] Add option to wipe existing metadata on bulk work update UCSCLibrary/dams_project_mgmt#164 

### Related Work 

Increase Test Coverage UCSCLibrary/dams_project_mgmt#76
