### ISSUE TITLE
UI/UX: Enhanced Support for Complex Objects

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/dams_project_mgmt#466]
### Descriptive Summary

This epic focuses on optimizing the users' experience with our complex objects, in particular our complex image objects.

### Acceptance Criteria

This is what done looks like:

* [x] UCSCLibrary/dams_project_mgmt#263 Detail User Needs of Child Works (includes mock ups)
* [ ] UCSCLibrary/ucsc-library-digital-collections#412 Update display settings to show child vs. parent metadata record on work display page
* [ ] UCSCLibrary/ucsc-library-digital-collections#396 Apply new child works page (desktop)
* [ ] UCSCLibrary/ucsc-library-digital-collections#397 Apply new child works page (Mobile) 
* [x] UCSCLibrary/dams_project_mgmt#358 Child Work Page Mock Up for Mobile 
* [x] UCSCLibrary/dams_project_mgmt#94 Ability to click through child Works from parent Work Page
* [ ] UCSCLibrary/ucsc-library-digital-collections#398 Implement New Search & Retrieval Experience for Complex Objects

### Related Work

This work can be done in parallel with work on the Configuration File Overhaul UCSCLibrary/dams_project_mgmt#77 and  Improving Search Functionality: Faceting & Sorting UCSCLibrary/dams_project_mgmt#323.
This work is preceded by User Interface Redesign UCSCLibrary/dams_project_mgmt#311.

**Comment by rmjaffe** [comment]
This epic is already underway; these tickets have been split off epic UCSCLibrary/dams_project_mgmt#323 and packaged as a separate epic.
