### ISSUE TITLE
Wrap Bulkrax work

### ISSUE THREAD

**Issue by bkiahstroud** [UCSCLibrary/dams_project_mgmt#520]
# Summary 

This ticket outlines the remaining work necessary to consider the Bulkrax work "done". 

# Acceptance Criteria 

**Need work:**

- [x] UCSCLibrary/ucsc-library-digital-collections#383 
- [ ] UCSCLibrary/ucsc-library-digital-collections#384 
- [ ] UCSCLibrary/ucsc-library-digital-collections#385
- [ ] UCSCLibrary/ucsc-library-digital-collections#369
- [ ] https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/387 
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/519 
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/517
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/514 
- [x] UCSCLibrary/dams_project_mgmt#521 
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/522
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/523
- [ ] https://github.com/UCSCLibrary/dams_project_mgmt/issues/538 
- [x] Release Bulkrax 3.0 / update in Gemfile 
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/524
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/525
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/528
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/532
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/533
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/534
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/539
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/556 

**Documentation:**

- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/505 
- [ ] https://github.com/UCSCLibrary/dams_project_mgmt/issues/506 
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/508 
- [x] https://github.com/UCSCLibrary/dams_project_mgmt/issues/507 

**Deploy:**

- [ ] Code successfully merged and deployed into Production

**Ingest:**

- [ ]  UCSCLibrary/ucsc-library-digital-collections#418 

**Training:**
- [ ] https://github.com/UCSCLibrary/ucsc-library-digital-collections/issues/409
(Updated this to a different ticket that is more clearly fixable by a Bulkrax round trip)

**Comment by rschwab** [comment]
Here's the [list of acceptance criteria](https://docs.google.com/document/d/1uYvkJNl89IvtiRwwEnaVzogMi6A6Y0eV0GOhGNcmkps/edit) UCSC came up with from an admin/librarian user perspective.

**Comment by rschwab** [comment]
UCSCLibrary/dams_project_mgmt#540 I would call a release blocker.
