### ISSUE TITLE
Project Documentation Overhaul

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#71]
### Descriptive Summary

Team determined that we would benefit from developing better documentation strategies and practices.  Work within this epic focuses on: 1) assessing and reorganizing existing documentation, and 2) developing and implementing recommended strategies.

### Acceptance Criteria

This is what done looks like:

- [x] Develop project documentation strategy #262
- [x] Team Drive clean-up #269 
- [x] Create test epics #270
- [x] Implement epics model #79
- [x] Update roadmap #58
