### ISSUE TITLE
(5) Implement epics model

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#79]
### Descriptive Summary

Team has decided to adopt the use/creation of epics to track our progress and to better organize our work.  Epic cards will "live" on the roadmap.

### Acceptance Criteria

Epic cards are needed for the following:
- [x] CONTENTdm Migration #288
- [x] UI/UX Overhaul #74 (consult with Jess)
- [x] Configuration File Overhaul #77 
- [x] Documentation Overhaul #71 (consult with Angelika & Sue)
- [x] SiteImprove (consult with Sue)
- [x] Development-side testing #76 & documentation standards #75 (consult with Ned & Ryan; possible deliverable from renewed relationship with Notch8)

### Related Work
#270 Testing out epics
 #58 Clean up Roadmap board
